name: batbuddy
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - intel-openmp=2025.0.0
  - libexpat=2.7.3
  - libffi=3.4.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libxml2=2.13.9
  - libzlib=1.3.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - numexpr=2.14.1
  - numpy-base=2.3.5
  - openssl=3.0.18
  - pandas=2.3.3
  - pip=25.3
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==12.1.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - psutil==7.2.1
      - pyparsing==3.3.1
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.16.3
      - sv-ttk==2.6.1
      - sympy==1.14.0
      - torch==2.9.1
      - torchvision==0.24.1
      - ttkthemes==3.3.0
      - typing-extensions==4.15.0
      - ultralytics==8.3.249
      - ultralytics-thop==2.0.18
      - urllib3==2.6.3
prefix: C:\Users\sanderb\AppData\Local\miniconda3\envs\batbuddy
